FROM golang:1.25

WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o factsnap ./cmd/api

CMD ["/app/factsnap"]
