// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreatePollOptions implements pgx.CopyFromSource.
type iteratorForCreatePollOptions struct {
	rows                 []CreatePollOptionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePollOptions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePollOptions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PollID,
		r.rows[0].Label,
		r.rows[0].Index,
	}, nil
}

func (r iteratorForCreatePollOptions) Err() error {
	return nil
}

func (q *Queries) CreatePollOptions(ctx context.Context, arg []CreatePollOptionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"poll_options"}, []string{"poll_id", "label", "index"}, &iteratorForCreatePollOptions{rows: arg})
}
