// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: location.sql

package sqlc

import (
	"context"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (location, name, address)
VALUES (
           point($1, $2), -- latitude, longitude
           $3,   -- name
           $4  -- address
       )
RETURNING id, location, name, address
`

func (q *Queries) CreateLocation(ctx context.Context, point float64, point_2 float64, name *string, address *string) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		point,
		point_2,
		name,
		address,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Name,
		&i.Address,
	)
	return i, err
}
