// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	ClerkUserID string
	Username    string
	Email       string
	DisplayName string
	Role        string
	AboutMe     *string
	AvatarUrl   *string
	CreatedAt   time.Time
}
