// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: response.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getResponsesByQuestionID = `-- name: GetResponsesByQuestionID :many
SELECT
  r.id,
  r.question_id,
  r.author_id,
  u.username,
  u.display_name,
  u.avatar_url,
  r.body,
  r.image_urls,
  r.created_at,
  r.edited_at
FROM responses r
JOIN users u ON u.id = r.author_id
WHERE r.question_id = $1
ORDER BY r.created_at DESC
`

type GetResponsesByQuestionIDRow struct {
	ID          uuid.UUID
	QuestionID  uuid.UUID
	AuthorID    string
	Username    string
	DisplayName string
	AvatarUrl   *string
	Body        string
	ImageUrls   []string
	CreatedAt   time.Time
	EditedAt    time.Time
}

func (q *Queries) GetResponsesByQuestionID(ctx context.Context, questionID uuid.UUID) ([]GetResponsesByQuestionIDRow, error) {
	rows, err := q.db.Query(ctx, getResponsesByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetResponsesByQuestionIDRow{}
	for rows.Next() {
		var i GetResponsesByQuestionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.AuthorID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Body,
			&i.ImageUrls,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
