// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, display_name, avatar_url, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, display_name, role, about_me, avatar_url, created_at
`

type CreateUserParams struct {
	ID          string
	Username    string
	Email       string
	DisplayName string
	AvatarUrl   *string
	Role        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AboutMe,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, role, about_me, avatar_url, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AboutMe,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserQuestionCount = `-- name: GetUserQuestionCount :one
SELECT COUNT(*) FROM questions
WHERE author_id = $1
`

func (q *Queries) GetUserQuestionCount(ctx context.Context, authorID string) (int, error) {
	row := q.db.QueryRow(ctx, getUserQuestionCount, authorID)
	var count int
	err := row.Scan(&count)
	return count, err
}

const getUserResponseCount = `-- name: GetUserResponseCount :one
SELECT COUNT(*) FROM responses
WHERE author_id = $1
`

func (q *Queries) GetUserResponseCount(ctx context.Context, authorID string) (int, error) {
	row := q.db.QueryRow(ctx, getUserResponseCount, authorID)
	var count int
	err := row.Scan(&count)
	return count, err
}
