// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	go_postgis "github.com/cridenour/go-postgis"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, display_name, avatar_url, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, display_name, role, about_me, avatar_url, created_at, expo_push_token, last_known_location
`

type CreateUserParams struct {
	ID          string
	Username    string
	Email       string
	DisplayName string
	AvatarUrl   *string
	Role        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AboutMe,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.ExpoPushToken,
		&i.LastKnownLocation,
	)
	return i, err
}

const deleteUserPushToken = `-- name: DeleteUserPushToken :exec
UPDATE users
SET expo_push_token = NULL
WHERE id = $1
`

func (q *Queries) DeleteUserPushToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserPushToken, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, role, about_me, avatar_url, created_at, expo_push_token, last_known_location
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AboutMe,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.ExpoPushToken,
		&i.LastKnownLocation,
	)
	return i, err
}

const getUserQuestionCount = `-- name: GetUserQuestionCount :one
SELECT COUNT(*) FROM questions
WHERE author_id = $1
`

func (q *Queries) GetUserQuestionCount(ctx context.Context, authorID string) (int, error) {
	row := q.db.QueryRow(ctx, getUserQuestionCount, authorID)
	var count int
	err := row.Scan(&count)
	return count, err
}

const getUserResponseCount = `-- name: GetUserResponseCount :one
SELECT COUNT(*) FROM responses
WHERE author_id = $1
`

func (q *Queries) GetUserResponseCount(ctx context.Context, authorID string) (int, error) {
	row := q.db.QueryRow(ctx, getUserResponseCount, authorID)
	var count int
	err := row.Scan(&count)
	return count, err
}

const getUsersInRadius = `-- name: GetUsersInRadius :many
SELECT id, expo_push_token
FROM users
WHERE ST_DWithin(
    last_known_location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    $3::float8
)
AND expo_push_token IS NOT NULL
`

type GetUsersInRadiusRow struct {
	ID            string
	ExpoPushToken *string
}

func (q *Queries) GetUsersInRadius(ctx context.Context, longitude float64, latitude float64, radiusMeters float64) ([]GetUsersInRadiusRow, error) {
	rows, err := q.db.Query(ctx, getUsersInRadius, longitude, latitude, radiusMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersInRadiusRow{}
	for rows.Next() {
		var i GetUsersInRadiusRow
		if err := rows.Scan(&i.ID, &i.ExpoPushToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $1
WHERE id = $2
RETURNING id, username, email, display_name, role, about_me, avatar_url, created_at, last_known_location, expo_push_token
`

type UpdateUserDisplayNameRow struct {
	ID                string
	Username          string
	Email             string
	DisplayName       string
	Role              string
	AboutMe           *string
	AvatarUrl         *string
	CreatedAt         time.Time
	LastKnownLocation *go_postgis.PointS
	ExpoPushToken     *string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, displayName string, iD string) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, displayName, iD)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AboutMe,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastKnownLocation,
		&i.ExpoPushToken,
	)
	return i, err
}

const updateUserLocation = `-- name: UpdateUserLocation :exec
UPDATE users
SET last_known_location = ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)
WHERE id = $1
`

func (q *Queries) UpdateUserLocation(ctx context.Context, iD string, longitude float64, latitude float64) error {
	_, err := q.db.Exec(ctx, updateUserLocation, iD, longitude, latitude)
	return err
}

const updateUserPushToken = `-- name: UpdateUserPushToken :exec
UPDATE users
SET expo_push_token = $2
WHERE id = $1
`

func (q *Queries) UpdateUserPushToken(ctx context.Context, iD string, expoPushToken *string) error {
	_, err := q.db.Exec(ctx, updateUserPushToken, iD, expoPushToken)
	return err
}
